apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-demo-app
  labels:
    app.kubernetes.io/name: go-demo-app
    app.kubernetes.io/instance: go-demo-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-demo-app
      app.kubernetes.io/instance: go-demo-app
  # If Prometheus Operator is in another namespace, uncomment and set:
  # namespaceSelector:
  #   matchNames:
  #     - <service-namespace>
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
