apiVersion: v1
kind: Service
metadata:
  name: go-demo-app
  labels:
    app.kubernetes.io/name: go-demo-app
    app.kubernetes.io/instance: go-demo-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: go-demo-app
    app.kubernetes.io/instance: go-demo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
