pipeline:
  name: CI/CD Pipeline
  identifier: ci_cd_pipeline
  projectIdentifier: your_project_id   # Replace this with your reference. Testing this.
  orgIdentifier: your_org_id           # Replace this with your reference
  tags: {}

  stages:
    - stage:
        name: Test Stage
        identifier: test_stage
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: your_k8s_connector_ref  # Replace this with your reference
              namespace: your_ci_namespace          # Replace this with your reference
          execution:
            steps:
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    registryRef: proj-harpov-docker-dev           # Replace this with your reference
                    image: parsontodd/harness-custom-runner       # Replace this with your reference
                    shell: Bash
                    command: |-
                      env
                      set -euo pipefail
                      go version
                      go test --coverprofile=coverage.txt ./...
                      ls -lat
              - step:
                  type: Run
                  name: Linting
                  identifier: Linting
                  spec:
                    registryRef: proj-harpov-docker-dev
                    image: parsontodd/harness-custom-runner:latest
                    shell: Bash
                    command: |-
                      set -euo pipefail
                      ls -laR /harness
                      golangci-lint version
                      golangci-lint run --timeout 5m0s --out-format checkstyle --issues-exit-code 0 > report.xml
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - report.xml
              - step:
                  type: Run
                  name: SAST
                  identifier: Gosec
                  spec:
                    connectorRef: harnessdockerhub
                    image: parsontodd/harness-custom-runner:latest
                    shell: Bash
                    command: |-
                      set -euo pipefail
                      gosec -no-fail -fmt=sonarqube -out report.json ./...
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - report.json              
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Docker Image
                  identifier: build_and_push_docker_image
                  spec:
                    repo: go-sample-app              # Replace this with your reference
                    tags:
                      - latest
                    caching: true
                    buildArgs:
                      REGISTRY_OVERRIDE: <+pipeline.variables.BASE_IMAGE_REGISTRY>
                      GO_VERSION: <+pipeline.variables.GO_VERSION>
    - stage:
        name: Deploy to GKE
        identifier: deploy_to_gke
        type: CD
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: your_k8s_connector_ref    # Replace this with your reference  
              namespace: your_deployment_namespace    # Replace this with your reference
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: Deploy
                  identifier: deploy
                  spec:
                    skipDryRun: false
                    timeout: 10m
                    manifests:
                      primary:
                        type: K8sManifest
                        spec:
                          store:
                            type: Git
                            spec:
                              connectorRef: your_git_connector    # Replace this with your reference
                              branch: main
                              paths:
                                - k8s/deployment.yaml
                                - k8s/service.yaml
                    values:
                      - name: image.tag
                        value: latest